better error handling

diff --git a/scripts/python/mkslurm_immerse b/scripts/python/mkslurm_immerse
--- a/scripts/python/mkslurm_immerse
+++ b/scripts/python/mkslurm_immerse
@@ -92,6 +92,12 @@ def main(args):
         eval "$CMD"
     }
 
+    get_timestep () {
+        TIMENAME=$1
+        TIMESTEP=$(grep -Eo '[0-9\.]+' "$TIMENAME")
+        echo "$TIMESTEP"
+    }
+
     # Convert days to hours
     if [ "$FREQRST" -lt 0 ]; then
         FREQRST=$(( FREQRST * -24 ))
@@ -104,7 +110,7 @@ def main(args):
     if [ "$PARENT_IT000" -eq 0 ]; then
         RESUBMIT=true
         if test -f "time.step"; then
-            PARENT_IT000=$(grep -Eo '[0-9\.]+' time.step)
+            PARENT_IT000=$(get_timestep time.step)
         fi
         PARENT_IT000=$(( PARENT_IT000 + 1 ))
     else
@@ -120,7 +126,6 @@ def main(args):
         # Use restarts
         edit_var ln_rstart ".true." ./*namelist_cfg
         edit_var ln_tsd_init ".false." ./namelist_cfg
-        edit_var ln_init_chfrpar ".false." ./*_namelist_cfg
 
         for NAMELIST in *namelist_cfg; do
             # Set start
@@ -138,16 +143,23 @@ def main(args):
             ICERST_IN=${OCERST_IN}_ice
             edit_var cn_ocerst_in "'${OCERST_IN}'" "$NAMELIST"
             edit_var cn_icerst_in "'${ICERST_IN}'" "$NAMELIST_ICE"
+
+            # Switch OFF init from parent
+            edit_var ln_init_chfrpar ".false." "$NAMELIST"
         done
 
     else
         # Start from rest
         edit_var ln_rstart ".false." ./*namelist_cfg
         edit_var ln_tsd_init ".true." ./namelist_cfg
-        edit_var ln_init_chfrpar ".true." ./*_namelist_cfg
         edit_var cn_ocerst_in "'dummy'" ./*namelist_cfg
         edit_var cn_icerst_in "'dummy'" ./*namelist_ice_cfg
         edit_var nn_it000 "1" ./*namelist_cfg
+
+        for NAMELIST in *namelist_cfg; do
+            # Switch ON init from parent
+            edit_var ln_init_chfrpar ".true." "$NAMELIST"
+        done
     fi
 
     # Edit nn_itend
@@ -258,17 +270,33 @@ def main(args):
     # Print stats
     sacct -j "$SLURM_JOB_ID" --units=G --format=JobID,JobName,NNodes,Elapsed,AveRSS,MaxRSS,MaxRSSNode,MaxRSSTask
 
-    # Move log file
-    mkdir -p LOGS/"$SLURM_JOB_ID"
-    mv {{*.dat,*output*,*.stat*,communication_report.txt}} LOGS/"$SLURM_JOB_ID"
+    # Move log files
+    if ls ./*ocean.output*; then
+        mkdir -p LOGS/"$SLURM_JOB_ID"
+        mv {{*.dat,*output*,*.stat*,communication_report.txt}} LOGS/"$SLURM_JOB_ID"
+    else
+        echo "E R R O R : NEMO ocean.output files are missing"
+        exit 1
+    fi
 
-    # Exit
+    # Check for errors
     ERROR=$(grep "E R R O R" {" ".join([os.path.join(path, 'LOGS/"$SLURM_JOB_ID"', "*ocean.output*") for path in args.D])} | wc -l)
-    if [ "$ERROR" -ne 0 ]; then
+    if [ "$ERROR" -gt 0 ]; then
         echo "E R R O R"
         grep -c "E R R O R" {" ".join([os.path.join(path, 'LOGS/"$SLURM_JOB_ID"', "*ocean.output*") for path in args.D])}
+        exit 1
     fi
-    exit "$ERROR"
+
+    # Check nn_itend vs time.step
+    for NAMELIST in *namelist_cfg; do
+        EXPECTED=$(get_var nn_itend "$NAMELIST")
+        TIMENAME=${{NAMELIST//namelist_cfg/time.step}}
+        ACTUAL=$(get_timestep "$TIMENAME")
+        if [ "$EXPECTED" -ne "$ACTUAL" ]; then
+            echo "E R R O R : $TIMENAME is $ACTUAL (expecting $EXPECTED)"
+            exit 1
+        fi
+    done
     """
     slurm += dedent(tail)
 
